name = "bltoncloudflare"
main = ".vercel/output/static/_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Static assets (images, css) must be served from a specific bucket or folder
# Workers Sites (legacy) configuration:
[site]
bucket = ".vercel/output/static"